default:
  #service
  # Do not use server_name as it is flask buildin
  service_name: micro_flask

  # listener
  listener_host: 0.0.0.0
  listener_port: 8888

  # For flask_smorest, see https://flask-smorest.readthedocs.io/en/latest/configuration.html
  # flask_smorest is a flask extension for building RESTful APIs and can show swagger doc.
  API_TITLE: micro_flask
  API_VERSION: 0.0.1
  OPENAPI_VERSION: 3.0.2
  OPENAPI_URL_PREFIX: /openapi
  OPENAPI_SWAGGER_UI_PATH: /swagger
  OPENAPI_SWAGGER_UI_URL: https://cdn.jsdelivr.net/npm/swagger-ui-dist@3.46.0/
  OPENAPI_REDOC_PATH: /redoc
  OPENAPI_REDOC_URL: https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js

  RESOURCE_MANAGER_SETTINGS: