version: '3'
networks:
  micro-net:
    external: true
services:
  wish-framework-portal:
    container_name: wish-framework-portal
#    build:
#      context: ../../
#      dockerfile: docker/eks/Dockerfile
#    image: wish-framework-portal:latest
    image: harbor.infra.wish-cn.com/wish/wish-framework-portal/api:latest
    user: ${BUILDUID:-1000}:${BUILDGID:-1000}
    environment:
      - "DOCKER_USER=${DOCKER_USER:-app}"
      - "EXTERNAL_IP=${EXTERNAL_IP}"
    hostname: "$USER"
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx:/etc/nginx/conf.d
      - config:/home/app/config
    networks:
      micro-net:
        ipv4_address: 192.168.100.100
    command:
      - /bin/bash
      - -c
      - cd /home/app/wish-framework-portal && make all && while true; do sleep 3600; done
volumes:
  nginx:
  config:
