FROM ubuntu:18.04 AS base

# Avoid confusing pip upgrade warning
ENV PIP_DISABLE_PIP_VERSION_CHECK=true

ENV DEBIAN_FRONTEND noninteractive
# ENV PYTHONDONTWRITEBYTECODE 1
RUN rm -f /etc/apt/sources.list.d/ubuntu-esm-infra-trusty.list

## apt installs
RUN apt-get update && apt-get install -y python3.7 python3-pip python3.7-dev build-essential git curl tzdata locales sudo

# for openapi generation
RUN apt-get update && apt-get install -y software-properties-common && \
  add-apt-repository -y ppa:openjdk-r/ppa && \
  apt update && \
  apt-get install -y openjdk-8-jre

## For pycurl
RUN apt-get update && apt-get install -y libcurl4-openssl-dev libssl-dev

## For postgres
RUN apt-get update && apt-get install -y libpq-dev

RUN echo "Asia/Shanghai" | tee /etc/timezone
RUN dpkg-reconfigure --frontend noninteractive tzdata

COPY wish_flask/docker/pip_cn.conf /etc/pip.conf
RUN locale-gen en_US.UTF-8

# pip 20.3.3, setuptools 51.3.3, wheel 0.36.2
ARG version_virtualenv=20.4.0
RUN pip3 install virtualenv==$version_virtualenv

RUN useradd --create-home app
# Put the app user from the base image in the sudo group for convenience
RUN usermod -a -G sudo app
# passwordless sudo
RUN sed -i '/^%sudo/c\%sudo ALL=(ALL:ALL) NOPASSWD:ALL' /etc/sudoers

# Create virtualenv
USER app
RUN mkdir /home/app/virtualenv
RUN virtualenv -p /usr/bin/python3.7 --no-download /home/app/virtualenv

FROM base AS fixuid
USER root
RUN curl -SsL https://github.com/boxboat/fixuid/releases/download/v0.3/fixuid-0.3-linux-amd64.tar.gz | tar xzv -C /usr/bin
RUN chown root:root /usr/bin/fixuid && \
    chmod 4755 /usr/bin/fixuid && \
    mkdir -p /etc/fixuid && \
    chown root:root /etc/fixuid && \
    printf "user: app\ngroup: app\npaths:\n  - /\n  - /home/app\n" > /etc/fixuid/config.yml
USER app
ENTRYPOINT ["/usr/bin/fixuid"]
