default:
  #service
  # Do not use server_name as it is flask buildin
  service_name: micro_flask


  API_TITLE: micro_flask
  API_VERSION: 0.0.1

  #listener
  listener_host: 0.0.0.0
  listener_port: 8888

  # flask_smorest
  OPENAPI_VERSION: 3.0.2
  OPENAPI_URL_PREFIX: /openapi
  OPENAPI_SWAGGER_UI_PATH: /swagger
  OPENAPI_SWAGGER_UI_URL: https://cdn.jsdelivr.net/npm/swagger-ui-dist@3.46.0/
  OPENAPI_REDOC_PATH: /redoc
  OPENAPI_REDOC_URL: https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js

  # flask
  PROPAGATE_EXCEPTIONS: false

  # wish-flask
  ## Settings for log exceptions
  log_exception:
    # TD logger for exceptions
    td_logger: td.exceptions
    # Log request body
    log_body: True
    # Log error trace
    log_trace: True
  ## Settings for logging request info
  log_request:
    body_limit: 4096
    # pattern for sanitize request body
    body_patterns:
      # For json
      - ((['\"])\w*?(?:secret|password)\w*?\2\s*:\s*(['\"])).*?(?<!\\)(?=\3)
      # For urlencoded
      - (&?\w*?(?:secret|password)\w*?=)[^&]*

  logging:
    version: 1
    disable_existing_loggers: False
    formatters:
      wish_formatter:
        (): zzzz.log.formatter.LogFormatter
        fmt: >-
          %(color)s[%(levelname)1.1s %(asctime)s %(process)d %(thread)d
          %(request_id)s %(request_tracing_id)s %(session_sign)s %(user_id)s
          %(name)s:%(lineno)d]%(end_color)s %(message)s
        datefmt: '%Y-%m-%d %H:%M:%S,%03d'
      td_weak_formatter:
        (): zzzz.log.formatter.LogFormatter
        fmt: >-
          %(color)s[%(levelname)1.1s %(asctime)s %(process)d %(thread)d
          %(request_id)s %(request_tracing_id)s %(session_sign)s %(user_id)s
          %(name)s:%(lineno)d]%(end_color)s ... eliminate body, use stdout_handler in td logger for details.
        datefmt: '%Y-%m-%d %H:%M:%S,%03d'
    filters:
      processor_args_length_cut_converter:
        '()': zzzz.log.filters.ProcessorArgsMaxLengthFilter
        max_arg_length: 500
      request_id_filter:
        (): zzzz.log.filters.RequestIdFilter
      request_tracing_id_filter:
        (): zzzz.log.filters.RequestTracingIdFilter
      session_sign_filter:
        (): zzzz.log.filters.SessionSignFilter
      user_id_filter:
        (): zzzz.log.filters.UserIdFilter
      request_client_filter:
        (): zzzz.log.filters.RequestClientFilter
    handlers:
      stdout_handler:
        class: logging.StreamHandler
        formatter: wish_formatter
        stream: ext://sys.stdout
        filters:
          - request_id_filter
          - request_tracing_id_filter
          - session_sign_filter
          - user_id_filter
          - request_client_filter
      td_weak_std_handler:
        class: logging.StreamHandler
        formatter: td_weak_formatter
        stream: ext://sys.stdout
        filters:
          - request_id_filter
          - request_tracing_id_filter
          - session_sign_filter
          - user_id_filter
          - request_client_filter

  RESOURCE_MANAGER_SETTINGS:
    apm:
      class: wish_micro_apm.apm.WishMicroApm
      setting:
        SERVER_URL: http://elasticapm-qa.bjs.i.wish.com
        SPAN_FRAMES_MIN_DURATION: 10ms
        STACK_TRACE_LIMIT: 300
        TRANSACTION_MAX_SPANS: 500
        API_REQUEST_TIME: 15s
        CENTRAL_CONFIG: true
        TRANSACTION_SAMPLE_RATE: 1.0
        DEBUG: true

dev:
  micro:
    dynaconf_merge: true



prod:
  # Disable openapi uri for prod env
  OPENAPI_URL_PREFIX:

  extensions:
    dynaconf_merge: true

  RESOURCE_MANAGER_SETTINGS:
    dynaconf_merge: true
