chartName: {{cookiecutter.project_name_hyphen}}
version: {{cookiecutter.project_version}}
wishAppLabel: {{cookiecutter.project_name_hyphen}}

image:
  repository: harbor.infra.wish-cn.com/wish/{{cookiecutter.project_name_hyphen}}/api
  tag: <tag>

deployments:
  - name: server
    replicaCount: 1
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
    env:
      - name: FLASK_ENV
        value: dev
    command:
      - /bin/bash
      - -c
      - "/production/{{cookiecutter.project_name}}/current/{{cookiecutter.project_name}}/bin/entrypoint-api.sh"
    ports:
      - name: http
        containerPort: {{cookiecutter.port}}
        protocol: TCP
    liveness:
      httpGet:
        path: /api/health
        port: http
    readiness:
      httpGet:
        path: /api/health
        port: http

services:
  - name: server
    ports:
      - name: http
        port: 80
        targetPort: http
        protocol: TCP
    deploymentRef: server

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
  hosts:
    - host: {{cookiecutter.project_name_hyphen}}.k8sdev.bjs.i.wish.com
      paths:
        - path: /
          pathType: Prefix
      serviceRef: server
      servicePort: 80
